### ISSUE TITLE
Fillable attributes for mass-assignment protection

### ISSUE THREAD

**Issue by ejunker** [lepikhinb/laravel-fluent#1]
I was thinking it might be possible to mark properties as fillable or guarded for Laravel's mass-assignment protection.

```php
class Person extends Model
{
    use Fluent;

    #[Fillable]
    public string $first_name;

    #[Fillable]
    public string $last_name;

    // not fillable since it does not have the Fillable attribute
    public bool $is_admin;
}
```

If you are not interested in adding this feature, no big deal.

**Comment by Namoshek** [comment]
@lepikhinb Can you explain why normal assignments are an issue? I don't think Laravel ever allows you to fully secure an attribute. Maybe with a mutator or so, but not directly. So this only needs to work for mass filling.
